import mercedescar from "../../../assets/mercedes-car.jpg";

const GLC="/GLC.jpeg"; // use as string, not imported

const engine = "/engine.jpeg"; // use as string, not imported
const keys="/keys.jpeg"; 
const tail="/tail.jpeg";
const rearbumper="/rearbumper.jpeg";
const rearseat="/rearseat.jpeg";
const dashboard="/dashboard.jpeg";
const tyres="/tyres.jpeg";
const frontright="/front.jpeg";
const frontleft="/frontcar.jpeg";
const rearright="/backside.jpeg";
const rearleft="/rear.jpeg";
const odo="/odo.jpg";


const sampleReport = {
  bookingId: "PUN210500011",
  customerName: "Rajanish Santani",
  engineer_name: "Rohit Mandhare",
  date: "2025-09-22",
  engineer_assignedSlot: "09:00 AM - 10:00 AM",
  address: "Pune",
  brand: "Mercedes-Benz",
  model: "GLC",
  carStatus: "New",
  vinNumber: "W1NKM0FB2SL010304",
  variant: "220d 4MATIC",
  transmissionType: "Automatic",
  fuelType: "Diesel",
  engineNumber: "K10BN4804320",
  keys: "2",
  vehicleScore: 8,
  scoreComment: "The vehicle is in excellent condition with no defects.",
  odo: 4484,
  live_distance_in_current_lock_block: 4484,
  tamperingStatus: "No Tampering",
  BHPs: 194,
  Airbags: 9,
  NCAP: "5 Star",
  Mileage: "18 kmpl",
  imageUrl: mercedescar,
  front_left_imageUrl: frontleft,
  rear_left_imageUrl:rearleft,
  rear_right_imageUrl: rearright,
  front_right_imageUrl: frontright,
  keys_imageUrl: keys,
  odo_imageUrl:odo,
  engineNumber_imageUrl: engine,
  vinNumber_imageUrl: engine,



  bonnet_paintThickness: 135,
  bonnet_issues: ["All Ok"],
  bonnet_repaint: false,
  bonnet_imageUrls: [],

  bumper_paintThickness: 132,
  bumper_issues: ["Stone Chipping", "Paint Chipping", "Paint Scratch"],
  rear_bumper_repaint: false,
  rear_bumper_imageUrls: [engine],

  front_left_fender_paintThickness: 129,
  front_left_fender_issues: ["Swirl marks"],
  front_left_fender_cladding_issues: ["All Ok"],
  front_left_fender_repaint: false,
  front_left_fender_imageUrls: [tail],

  front_left_door_paintThickness: 142,
  front_left_door_issues: ["All Ok"],
  front_left_door_cladding_issues: ["All Ok"],
  front_left_door_repaint: false,
  front_left_door_imageUrls: [],

  rear_left_door_paintThickness: 139,
  rear_left_door_issues: ["All Ok"],
  rear_left_door_cladding_issues: ["All Ok"],
  rear_left_door_repaint: false,
  rear_left_door_imageUrls: [],

  rear_left_quarter_panel_paintThickness: 135,
  rear_left_quarter_panel_issues: ["All Ok"],
  rear_left_quarter_panel_cladding_issues: ["All Ok"],
  rear_left_quarter_panel_repaint: false,
  rear_left_quarter_panel_imageUrls: [],

  boot_paintThickness: 141,
  boot_issues: ["All Ok"],
  boot_imageUrls: [],

  rear_bumper_paintThickness: 146,
  rear_bumper_issues: ["Paint Chipping","Stone Chipping"],
  rear_bumper_repaint: false,
  rear_bumper_imageUrls: [],

  rear_right_quarter_panel_paintThickness: 132,
  rear_right_quarter_panel_issues: ["All Ok"],
  rear_right_quarter_panel_cladding_issues: ["All Ok"],
  rear_right_quarter_panel_repaint: false,
  rear_right_quarter_panel_imageUrls: [],

  rear_right_door_paintThickness: 142,
  rear_right_door_issues: ["All Ok"],
  rear_right_door_cladding_issues: ["All Ok"],
  rear_right_door_repaint: false,
  rear_right_door_imageUrls: [],

  front_right_door_paintThickness: 138,
  front_right_door_issues: ["All Ok"],
  front_right_door_cladding_issues: ["All Ok"],
  front_right_door_repaint: false,
  front_right_door_imageUrls: [],

  front_right_fender_paintThickness: 135,
  front_right_fender_issues: ["All Ok"],
  front_right_fender_cladding_issues: ["All Ok"],
  front_right_fender_repaint: false,
  front_right_fender_imageUrls: [],

  roof_paintThickness: 147,
  roof_issues: ["All Ok"],
  roof_repaint: false,
  roof_imageUrls: [],

  front_windshield_brand: "AGC",
  front_windshield_manufacturingDate: "04/25",
  front_windshield_issues: ["All Ok"],
  front_windshield_imageUrls: [],

  front_left_door_glass_brand: "AGC",
  front_left_door_glass_manufacturingDate: "04/25",
  front_left_door_glass_issues: ["All Ok"],
  front_left_door_glass_imageUrls: [],

  left_side_orvm_brand: "",
  left_side_orvm_manufacturingDate: "",
  left_side_orvm_issues: ["All Ok"],
  left_side_orvm_imageUrls: [],

  rear_left_door_glass_brand: "AGC",
  rear_left_door_glass_manufacturingDate: "04/25",
  rear_left_door_glass_issues: ["All Ok"],
  rear_left_door_glass_imageUrls: [],

  rear_left_quarter_glass_brand: "AGC",
  rear_left_quarter_glass_manufacturingDate: "04/25",
  rear_left_quarter_glass_issues: ["All Ok"],
  rear_left_quarter_glass_imageUrls: [],

  rear_windshield_brand: "AGC",
  rear_windshield_manufacturingDate: "04/25",
  rear_windshield_issues: ["All Ok"],
  rear_windshield_imageUrls: [],

  rear_right_quarter_glass_brand: "AGC",
  rear_right_quarter_glass_manufacturingDate: "04/25",
  rear_right_quarter_glass_issues: ["All Ok"],
  rear_right_quarter_glass_imageUrls: [],

  rear_right_door_glass_brand: "AGC",
  rear_right_door_glass_manufacturingDate: "04/25",
  rear_right_door_glass_issues: ["All Ok"],
  rear_right_door_glass_imageUrls: [],

  front_right_door_glass_brand: "AGC",
  front_right_door_glass_manufacturingDate: "04/25",
  front_right_door_glass_issues: ["All Ok"],
  front_right_door_glass_imageUrls: [],

  right_side_orvm_brand: "",
  right_side_orvm_manufacturingDate: "",
  right_side_orvm_issues: ["All Ok"],
  right_side_orvm_imageUrls: [],

  sunroof_glass_brand: "AGC",
  sunroof_glass_manufacturingDate: "04/25",
  sunroof_glass_issues: ["All Ok"],
  sunroof_glass_toggle: true,
  sunroof_glass_imageUrls: [],

  rubber_bonnet_issues: ["All Ok"],
  rubber_front_left_door_issues: ["Worn out"],
  rubber_rear_left_door_issues: ["All Ok"],
  rubber_boot_issues: ["All Ok"],
  rubber_rear_right_door_issues: ["All Ok"],
  rubber_front_right_door_issues: ["All Ok"],
  rubber_front_wiper_issues: ["All Ok"],
  rubber_rear_wiper_issues: ["All Ok"],
  rubber_rear_wiper_toggle: true,
  rubber_sunroof_issues: ["All Ok"],
  rubber_sunroof_toggle: true,

  seat_driver_issues: ["All Ok"],
  seat_driver_imageUrls: [],
  seat_driver_head_rest_issues: ["All Ok"],
  seat_driver_head_rest_imageUrls: [],
  seat_codriver_issues: ["All Ok"],
  seat_codriver_imageUrls: [],
  seat_codriver_head_rest_issues: ["All Ok"],
  seat_codriver_head_rest_imageUrls: [],
  seat_rear_issues: ["Soil Marks"],
  seat_rear_imageUrls: [rearseat],
  seat_rear_head_rest_issues: ["All Ok"],
  seat_rear_head_rest_imageUrls: [],
  seat_third_row_issues: ["All Ok"],
  seat_third_row_imageUrls: [],
  seat_third_row_toggle: true,
  seat_third_row_head_rest_issues: ["All Ok"],
  seat_third_row_head_rest_imageUrls: [],
  seat_roof_issues: ["All Ok"],
  seat_roof_imageUrls: [],
  seat_sunroof_issues: ["All Ok"],
  seat_sunroof_imageUrls: [],

  seatbelt_driver_issues: ["All Ok"],
  seatbelt_driver_imageUrls: [],
  seatbelt_codriver_issues: ["All Ok"],
  seatbelt_codriver_imageUrls: [],
  seatbelt_rear_left_passenger_issues: ["All Ok"],
  seatbelt_rear_left_passenger_imageUrls: [],
  seatbelt_rear_right_passenger_issues: ["All Ok"],
  seatbelt_rear_right_passenger_imageUrls: [],
  seatbelt_third_row_issues: ["All Ok"],
  seatbelt_third_row_imageUrls: [],
  seatbelt_third_row_toggle: false,

  plastic_driver_door_issues: ["All Ok"],
  plastic_driver_door_imageUrls: [],
  plastic_codriver_door_issues: ["All Ok"],
  plastic_codriver_door_imageUrls: [],
  plastic_rear_left_passenger_door_issues: ["All Ok"],
  plastic_rear_left_passenger_door_imageUrls: [],
  plastic_rear_right_passenger_door_issues: ["All Ok"],
  plastic_rear_right_passenger_door_imageUrls: [],
  plastic_third_row_issues: ["All Ok"],
  plastic_third_row_imageUrls: [],
  plastic_third_row_toggle: false,
  plastic_dashboard_issues: ["Scratches"],
  plastic_dashboard_imageUrls: [dashboard],
  plastic_gear_console_issues: ["All Ok"],
  plastic_gear_console_imageUrls: [],
  plastic_steering_issues: ["All Ok"],
  plastic_steering_imageUrls: [],
  plastic_ac_vents_issues: ["All Ok"],
  plastic_ac_vents_imageUrls: [],
  plastic_rear_ac_vents_issues: ["All Ok"],
  plastic_rear_ac_vents_imageUrls: [],
  plastic_irvm_issues: ["All Ok"],
  plastic_irvm_imageUrls: [],

  feature_parking_sensors_front_available: true,
  feature_parking_sensors_front_issueObserved: false,
  feature_parking_sensors_rear_available: true,
  feature_parking_sensors_rear_issueObserved: false,
  feature_front_view_camera_available: true,
  feature_front_view_camera_issueObserved: false,
  feature_rear_view_camera_available: true,
  feature_rear_view_camera_issueObserved: false,
  feature_camera_360_available: false,
  feature_camera_360_issueObserved: false,
  feature_touch_screen_available: true,
  feature_touch_screen_issueObserved: false,
  feature_speakers_available: true,
  feature_speakers_issueObserved: false,
  feature_electric_orvm_available: true,
  feature_electric_orvm_issueObserved: false,
  feature_auto_dimming_irvm_available: true,
  feature_auto_dimming_irvm_issueObserved: false,
  feature_ventilated_seat_driver_available: true,
  feature_ventilated_seat_driver_issueObserved: false,
  feature_ventilated_seat_codriver_available: true,
  feature_ventilated_seat_codriver_issueObserved: false,
  feature_ventilated_seat_rear_available: false,
  feature_ventilated_seat_rear_issueObserved: false,

  live_engine_load_toggle: true,
  live_engine_load: "23",
  live_idle_rpm_toggle: true,
  live_idle_rpm: 873,
  live_battery_voltage: "12.3",
  live_distance_since_code_clear: 4484,
  live_distance_in_current_lock_block: 4484,

  engine_issues: "None",
  transmission_issues: "None",
  brakes_issues: "None",
  diagnostic_codes: ["U0146"],

  fluid_coolant_withinRange: true,
  fluid_coolant_contamination: false,
  fluid_engineOil_withinRange: true,
  fluid_engineOil_contamination: true,
  fluid_brakeOil_withinRange: true,
  fluid_brakeOil_contamination: false,
  fluid_washerFluid_withinRange: true,
  fluid_washerFluid_contamination: false,

  tyre_front_left_brand: "Conteinental",
  tyre_front_left_subBrand: "ContiSportContact",
  tyre_front_left_variant: "Eco",
  tyre_front_left_issues: ["Uneven Wear"],
  tyre_front_left_size: "235/55R19",
  tyre_front_left_treadDepth: 6.28,
  tyre_front_left_manufacturingDate: "2024-03-12",
  tyre_front_left_imageUrls: [tyres],

  tyre_rear_left_brand: "Conteinental",
  tyre_rear_left_subBrand: "ContiSportContact",
  tyre_rear_left_variant: "Eco",
  tyre_rear_left_issues: ["All Ok"],
  tyre_rear_left_size: "235/55R19",
  tyre_rear_left_treadDepth: 6.28,
  tyre_rear_left_manufacturingDate: "2024-03-12",
  tyre_rear_left_imageUrls: [],

  tyre_rear_right_brand: "Conteinental",
  tyre_rear_right_subBrand: "ContiSportContact",
  tyre_rear_right_variant: "Eco",
  tyre_rear_right_issues: ["Uneven Wear"],
  tyre_rear_right_size: "235/55R19",
  tyre_rear_right_treadDepth: 6.42,
  tyre_rear_right_manufacturingDate: "2024-03-12",
  tyre_rear_right_imageUrls: [tyres],

  tyre_front_right_brand: "Conteinental",
  tyre_front_right_subBrand: "ContiSportContact",
  tyre_front_right_variant: "Eco",
  tyre_front_right_issues: ["All Ok"],
  tyre_front_right_size: "235/55R19",
  tyre_front_right_treadDepth: 6.24,
  tyre_front_right_manufacturingDate: "2024-03-12",
  tyre_front_right_imageUrls: [],

  tyre_spare_brand: "Conteinental",
  tyre_spare_subBrand: "ContiSportContact",
  tyre_spare_variant: "Eco",
  tyre_spare_issues: ["All Ok"],
  tyre_spare_size: "235/55R19",
  tyre_spare_treadDepth: 6.16,
  tyre_spare_manufacturingDate: "2023-12-01",
  tyre_spare_imageUrls: [],
  tyre_spare_toggle: true,

  other_observations: "1. DTC code found U0146 Network Communication Error. 2. Scratches found on Rear Left Wheel.",
};

export default sampleReport;